### ISSUE TITLE
prompt node style proposal

### ISSUE THREAD

**Issue by ltdrdata** [FizzleDorf/ComfyUI_FizzNodes#1]
![prompts](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/128333288/10398395-e912-4388-871f-67a10b6dd4bd)

Wouldn't it be more intuitive to represent sequences through nodes, leveraging the strengths of ComfyUI, rather than simply porting deforum? By expressing them in this way, it seems like it would be useful even when changing the order of the sequence.

**Comment by FizzleDorf** [comment]
While it's true you could easily swap around the prompt order, it wouldn't be a good fit for what I am planning to do with the nodes in the future.  I can release them as an alternate set of nodes and label both methods accordingly. I also want to keep this familiar to the folks coming from A1111 and are used to the Deforum style of prompting. Once I cross out a couple of things on the TODO list I'll take a look into implementing this.

**Comment by ltdrdata** [comment]
> While it's true you could easily swap around the prompt order, it wouldn't be a good fit for what I am planning to do with the nodes in the future. I can release them as an alternate set of nodes and label both methods accordingly. I also want to keep this familiar to the folks coming from A1111 and are used to the Deforum style of prompting. Once I cross out a couple of things on the TODO list I'll take a look into implementing this.

It's true. Providing functionality that is compatible with the existing system takes priority for now.

**Comment by StefanoMartin** [comment]
I just did a PR that accomplishes something similar.

https://github.com/FizzleDorf/ComfyUI_FizzNodes/pull/31
