### ISSUE TITLE
import failed 

### ISSUE THREAD

**Issue by fresno808** [FizzleDorf/ComfyUI_FizzNodes#105]
No matter how many times Ive tried installing and reinstalling, either through manager or git pull, I get an import error. Any ideas on how to fix it?

**Comment by fresno808** [comment]
Cannot import C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
[comfy_mtb] | INFO -> loaded 78 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Traceback (most recent call last):
  File "C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\djtid\\OneDrive\\Documents\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ControlNet-LLLite-ComfyUI\\__init__.py'

**Comment by FizzleDorf** [comment]
numpy was removed from the comfyui requirements. try reinstalling the requirements.txt file with pip.

**Comment by FizzleDorf** [comment]
I'll be closing this issue for no response. If you are still having issues, make a reply here I'll re-open the issue.

**Comment by fresno808** [comment]
I reinstalled requirements with pip and got this.

C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes>python -m pip install -r requirements.txt
Requirement already satisfied: numpy in c:\users\djtid\appdata\roaming\python\python311\site-packages (from -r requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: pandas in c:\users\djtid\appdata\roaming\python\python311\site-packages (from -r requirements.txt (line 2)) (2.2.1)
Requirement already satisfied: numexpr in c:\users\djtid\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 3)) (2.10.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\djtid\appdata\roaming\python\python311\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\djtid\appdata\roaming\python\python311\site-packages (from pandas->-r requirements.txt (line 2)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\djtid\appdata\roaming\python\python311\site-packages (from pandas->-r requirements.txt (line 2)) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\djtid\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.16.0)

**Comment by FizzleDorf** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI\init.py'`
try reinstalling controlnetllite

**Comment by FizzleDorf** [comment]
actually, can you find the rest of the error? The message where it says it cannot import fiznodes is the tail end of it. you can find it easier with `ctrl + f` then search `fizznodes`

**Comment by fresno808** [comment]
i just copied everything that says fizznodes

 File "C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 7, in <module>
    import pandas as pd
  File "C:\Users\djtid\AppData\Roaming\Python\Python311\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\djtid\AppData\Roaming\Python\Python311\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\djtid\AppData\Roaming\Python\Python311\site-packages\pandas\_libs\__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Cannot import C:\Users\djtid\OneDrive\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
