### ISSUE TITLE
PromptSchedule & StringSchedule will not replace pw_a / pw_b / pw_c / pw_d placeholders

### ISSUE THREAD

**Issue by a1lazydog** [FizzleDorf/ComfyUI_FizzNodes#106]
Because PromptSchedule & StringSchedule sets the start_frame / end_frame to 0,:

https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/27b00b936413d7c04d33eee03a55f81040221cd5/ScheduledNodes.py#L92

https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/27b00b936413d7c04d33eee03a55f81040221cd5/ScheduledNodes.py#L263

it'll never run through this loop:
 
https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/27b00b936413d7c04d33eee03a55f81040221cd5/BatchFuncs.py#L183-L185

Because it's a `range(0, 0)`
And thus would never replace those strings in any of the strings

**Comment by FizzleDorf** [comment]
thanks for the heads up! I pushed the fixes here: 0a7e9bc
