### ISSUE TITLE
Batch Prompt Schedule AnemateDiff with SDXL checkpoint not working ?

### ISSUE THREAD

**Issue by AdamChonko** [FizzleDorf/ComfyUI_FizzNodes#107]
Hi :)

I am completely new to comfy ui and sd. I have an SDXL checkpoint, video input + depth map controlnet and everything set to XL models but for some reason Batch Prompt Schedule is not working, it seems as its only taking the first prompt.

I want to achieve morphing effect between various prompts within my reference video. Here is my worlkflow screenshots + json workflow and result so far:

https://github.com/user-attachments/assets/56446f14-eeac-4be5-8bd0-d7a8efc56b45

![1](https://github.com/user-attachments/assets/4007f579-f742-41da-9b90-0571c033feb4)
![2](https://github.com/user-attachments/assets/82cd6993-d0a2-4b18-aa6d-e58e1a7086ea)
![3](https://github.com/user-attachments/assets/3d37f9bd-24cf-40d3-8ea8-2c539334c102)
<img width="791" alt="4" src="https://github.com/user-attachments/assets/102e09ad-b9cb-48ce-8649-61fb77591e58">

[sdxlbatchprompt_workflow.json](https://github.com/user-attachments/files/16520375/sdxlbatchprompt_workflow.json)

Thanks a looooot, you would save my life, its for a music video and the deadline is dangerously close.

**Comment by FizzleDorf** [comment]
at the moment, I don't see the issue you are describing where the prompt is the same across the whole batch however this is odd behaviour with how the prompt is applied
this is an example I put together so it's isolated. the frames are clearly changing 
![image](https://github.com/user-attachments/assets/c4db7544-0e1d-4152-b3f5-b9d100ecdd17)

however, both inputs with the same prompt schedule should be the same results but that isn't the case when using the regular batch scheduler
![image](https://github.com/user-attachments/assets/f3184485-3e47-4e75-a734-e416a8b84121)

for now I would suggest you use the regular batch scheduler so you can finish your project while I look into this.

**Comment by AdamChonko** [comment]
I am seem to have problem with "connecting the prompt" with the video reference (depth controlnet and ipadapter - xl model), I managed the batch prompt to work without the ip adapter and controlnet:

https://github.com/user-attachments/assets/31d1cb1f-527e-41b8-ae34-04057cc53d0a

But its somehow "struggling" with IPAdapter and Depth map controlnet - as the batch prompt schedule does not apply:

https://github.com/user-attachments/assets/a85253d2-83d1-4ab2-a988-10996d03f05f

Couldnt it be because IPAdapter and Depthmap somehow "holds" the structure of reference video and therefore the batch prompt schedule "cant" change it anymore ?

This is the loaded reference video: 

https://github.com/user-attachments/assets/deacd3a3-f826-4fb0-a4f6-fc61104463a2

And this is my current workflow: 
[evenmessierworkflow.json](https://github.com/user-attachments/files/16530027/evenmessierworkflow.json)

**Comment by FizzleDorf** [comment]
This might not be an issue with my nodes in particular. My suggestion is ease off on the strength, start_steps and/or end_steps of the controlnet and ipadapter so they don't overpower the token conditioning. this might need multiple tests to find a good sweet spot
