### ISSUE TITLE
BatchPromptScheduleEncodeSDXL, sizes of tensors doesn't match

### ISSUE THREAD

**Issue by beiwilliam** [FizzleDorf/ComfyUI_FizzNodes#108]
Hi. First of all, I want to thank you for your contribution.

I am work with animatediff + prompt travel, but i got this ↓

![image](https://github.com/user-attachments/assets/89e95246-7a85-4963-a733-214f97e0f2cc)

![image](https://github.com/user-attachments/assets/0cfc545d-155d-4e97-aea3-211117a01be1)

I am confused about the situation in the picture, why is the prompt blank? Is this normal? 

Thanks.

**Comment by FizzleDorf** [comment]
The tensor sizes are a problem I am looking into. The empty prompt showing in the debug is the negative prompt output but since you are using a different negative conditioning it just prints empty. I can add another bool to print the POS or NEG separately.

**Comment by FizzleDorf** [comment]
I can't seem to replicate it after the first commit I put out tonight so try again after updating and let me know if there are still issues with the tensor size.

**Comment by beiwilliam** [comment]
Hi, I understand the situation.
After updating to the newest version, there is other error.

The size of pooled_out is 0.
![image](https://github.com/user-attachments/assets/f63a6f6a-13e4-4ca4-82ef-08f7fc41c3d0)

**Comment by FizzleDorf** [comment]
I just comitted c0ec3632430ea03476e66b8de5f6e967159efb81, try pulling and trying again. if you are still getting errors can you please share a workflow so I can see what is going on?

**Comment by beiwilliam** [comment]
Still. 👀

Workflow: [here](https://pastebin.com/3PV0y4uN).

I appreciate your kind assistance.

**Comment by beiwilliam** [comment]
The node Batch Prompt Schedule(SD15), which was working normally, encountered the same error after updating to c0ec363.

![image](https://github.com/user-attachments/assets/a02210dd-5728-4a4f-8307-07e4be589065)

**Comment by FizzleDorf** [comment]
#109 is the same issue and I just added some code to handle the start and end_frame cases. If you are still having trouble after pulling, post the results in #109 so this new issue doesn't get mixed in with your original one.
