### ISSUE TITLE
BUG: Text Node inputs fail

### ISSUE THREAD

**Issue by Duemellon** [FizzleDorf/ComfyUI_FizzNodes#11]
When I convert the text, app text or the pre to an input the connected text nodes toss an error about length or something. I've been using TTN Text node. I tried converting to STRING between but still fails.

When I convert text-string (WAS) the production begins but the end result is a black box/image.

Even WAS Text multiline > WAS string gives error

**RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 5 in the list.**

**Comment by FizzleDorf** [comment]
yes, animate diff is limited to 75 tokens. I'd suggest checking the AD repo issues instead.

**Comment by Duemellon** [comment]
Here's my json
[BPSchedTextError.zip](https://github.com/FizzleDorf/ComfyUI_FizzNodes/files/12805106/BPSchedTextError.zip)

**Comment by Duemellon** [comment]
Typo addressed:

initial result
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113479041/7cb776c6-a78f-4f01-8249-5aae13e3a682)

Copy & paste the exact text to the TTN Text node into empty input for BPSched text widget then run (t2t)...
This time it produced something. 
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113479041/a53b948f-21a2-4cf3-aa84-8ab39ad88e13)

When I copied the text I just had in the TTN Text node to the BPSched (returning text to widget) I get:
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113479041/1cb35069-6f5d-4cd1-b601-8c4cdf01baf2)
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113479041/786a8f32-4a63-4b7f-a569-596ca23dc01f)

If I copy & paste the text from the BPSched above, which worked previously, I get this error still.
If I type it in, manually, character-for-character, I get this error.
When I hook the previous BPSched, which remained unchanged I goes on.

It's as if the text "corrupted" the 2nd BPSched in a hard way

**Comment by FizzleDorf** [comment]
This is a very specific odd case but I'll leave this open. It could be related to #5 but I am looking into new features first befor looking into custom node compatibility. Once some major additions are done I'll look into this.

**Comment by FizzleDorf** [comment]
this issue is solved in the latest commit
