### ISSUE TITLE
Index hold "0.0:" not working as expected

### ISSUE THREAD

**Issue by felixniemeyer** [FizzleDorf/ComfyUI_FizzNodes#115]
I'm expecting "0.0:" to hold that prompt until the next specification. 

However, I observe, that it holds for only one frame and then switches over to the next already.

Have a look at the prompts and the comfy output it produces: 

![image](https://github.com/user-attachments/assets/dfea00b9-b3ab-4a6e-bb9b-af9551a07887)

![image](https://github.com/user-attachments/assets/2b3c9a35-2a05-4824-ba24-e8bc891c2197)

The first prompt appears only on one line. I had expected it to go from 0.0 to 0.33

**Comment by FizzleDorf** [comment]
This is the animate diff implementation of the prompt scheduling, not fizznodes.

**Comment by felixniemeyer** [comment]
You're completely right, 
opened an issue there: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/issues/487
