### ISSUE TITLE
Error when using long prompt and short prompt together

### ISSUE THREAD

**Issue by Bochu3** [FizzleDorf/ComfyUI_FizzNodes#13]
I am getting error when trying to use long prompt and short together. This is the error I got
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/121131123/dcf503d0-bb09-447e-aa16-540fc3f014f8)

This is the prompt I am using to test and getting error.
"0": "portrait, 1girl",
"4": "maximum details, cinematic, (abstract art:1.1), deep shadow,1 girl, adult russian woman, grey eyes, blonde sleek hair, Style-GravityMagic, looking away, solo, upper body, detailed background, detailed face, (sovietpunkai, soviet communist theme:1.1), eyes ablaze with dark power, blood sorcerer, scarlet clothes, cape, hood, dynamic movement, evil smile, red glyphs swirling in the air, floating particles, blood droplets, scarlet color scheme, blood dripping, sacrificial altar, in background, glowing red power, nighttime, symmetrical composition, cinematic atmosphere,",
"8": "portrait, 1girl"

**Comment by FizzleDorf** [comment]
This is an issue with Animate Diff not being able to do chunks over 75 tokens. The schedule works normally without animate diff.

**Comment by FizzleDorf** [comment]
I've updated the repo with a fix
