### ISSUE TITLE
local variable 'value' referenced before assignment

### ISSUE THREAD

**Issue by IdeaFridge** [FizzleDorf/ComfyUI_FizzNodes#14]
local variable 'value' referenced before assignment " error pops up

it says it couldn't get the value from ScheduledNodes.py
key_frame_series[i] = numexpr.evaluate(value) if not is_single_string else self.sanitize_value(value)

![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/145101935/4006afc5-d900-435b-a0d6-57fb35826d6f)

Im at a loss :(

**Comment by FizzleDorf** [comment]
that is one error. The 0 frame needs to be scheduled to fix that error. The second one that will come up is because the pw_b input needs some value when it's converted to an input. Otherwise, convert it to a widget so it just recieves a static number.
