### ISSUE TITLE
BatchPromptSchedule tensor match error

### ISSUE THREAD

**Issue by brbbbq** [FizzleDorf/ComfyUI_FizzNodes#16]
I'm getting this error when using the BatchPromptSchedule node and the prompts are different lengths:

"Error occurred when executing BatchPromptSchedule:
Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 18 in the list."

![231017-131143-chrome](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/135537138/820a869c-8b00-4db7-8995-7e31ea997323)

Do the prompts need to contain the same number of 77 token chunks, or is this a bug?

**Comment by Adam34332** [comment]
I also encountered this problem. Please ask the author to remove the limitation on the description length and the matching problem. If the prompt word is too long, this error will be reported.

**Comment by FizzleDorf** [comment]
I would like to add this is a limitation with animate diff, not the schedule.

**Comment by FizzleDorf** [comment]
Just fyi I fixed this in the latest commit
