### ISSUE TITLE
black screen in output

### ISSUE THREAD

**Issue by ksy2345** [FizzleDorf/ComfyUI_FizzNodes#18]
Yesterday everything was fine, but today I generated absolutely the same thing, but it only resulted in a black screen, although I didn’t change anything. And this error appeared in the terminal, although it didn’t exist yesterday . 
   D:\comfuUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py:54: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(Masterpiece, best quality:1.2), closeup, a girl dancing through forest  spring day, cherryblossoms ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  cur_prompt_series[i] = str(pre_text) + " " + str(current_prompt) + " " + str(app_text)
D:\comfuUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py:55: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(Masterpiece, best quality:1.2), closeup, a girl dancing through forest  spring day, cherryblossoms ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  nxt_prompt_series[i] = str(pre_text) + " " + str(current_prompt) + " " + str(app_text).

**Comment by BuffMcBigHuge** [comment]
I was dealing with a similar issue. I was seeing a "Strength: nan". I deleted the node and recreated it, and the problem was solved.

**Comment by FizzleDorf** [comment]
this warning is unrelated to the problem. Do you have an example of the workflow you were having issues with and have you tried after updating ComfyUI, Animate Diff and this repo?
