### ISSUE TITLE
BatchPromptSchedule has no effect

### ISSUE THREAD

**Issue by 631557fcd** [FizzleDorf/ComfyUI_FizzNodes#21]
Kubuntu System, Comfyui shares venv with Automatic1111, RTX3060 12GB, 32GB RAM, xformers enabled

BatchPromptSchedule has no influence on the sampler. It seems as if only the last prompt is taken into account. I have tried it with different diffusion models, motion outputs as expected but there is no change in the generated images. I removed/reinstalled FizzNodes. This had no effect. There are no errors in the console output.

Any help would be appreciated.

I attached two examples and the outputs from my system
![AnimateDiff_00062_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/83867393/658e9134-9b71-4510-9de7-e17880d83892)
![AnimateDiff_00065_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/83867393/81aa3de5-d2fa-49c6-966e-d6026ee8a57c)
![BatchPromptTest01](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/83867393/518ea3e5-e186-40e7-9736-920abac242c7)
![BatchPromptTest02](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/83867393/38c56d67-eb57-4708-8638-676c599480f2)

**Comment by FizzleDorf** [comment]
This works fine on my install using your workflow. I just want to make sure you are on the latest versions of: ComfyUI, Animate Diff Evolved, and this repo.
![Capture](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/9ad4c754-e7e2-4cce-8f5d-bf58f9c266e7)

**Comment by 631557fcd** [comment]
Thanks for the reply. I updated via the manager in comfyui. The manager tells me all extensions are up to date. Comfyui seems to be updated as well, ComfyUI Revision: 1617 [d1d2fea8] | Released on '2023-10-25'.

**Comment by lonelydonut** [comment]
Facing a similar phenomenon, same workflow. All nodes updated.

**Comment by nomadoor** [comment]
I'm having the same problem.
Both ComfyUI and custom nodes are the latest ver
However, it feels like the whole prompt is mixed up, not the last prompt
![fizznode](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/124905471/d9b9b530-15e7-473a-bd90-45a533a83627)
[PromptTravel.json](https://github.com/FizzleDorf/ComfyUI_FizzNodes/files/13170831/PromptTravel.json)

**Comment by FizzleDorf** [comment]
I've solved the issue this afternoon. Please update to latest.

**Comment by 631557fcd** [comment]
Thank you! Now it works!
