### ISSUE TITLE
Batch Prompt Schedule not moving to the next prompt

### ISSUE THREAD

**Issue by sixex44** [FizzleDorf/ComfyUI_FizzNodes#22]
Hello, BatchPromptSchedule in Comfy UI is only running the first prompt, I had it working previously and now when running a json that did go through the scheduled prompts it will only use the first.

**Comment by FizzleDorf** [comment]
Can you verify you are on the latest version? This was a problem a few days ago when I was trying to increase the token limit for batches. Latest should not have this problem still.

**Comment by sixex44** [comment]
yes, I deleted whatever version I was on and installed the current and
still getting the issue. Everything was working fine for me until a few
days ago. Thanks

**Comment by FizzleDorf** [comment]
I can't seem to replicate the issue. Can you send me your workflow or something similar for testing?

**Comment by sixex44** [comment]
here's my workflow, thank you.

**Comment by sixex44** [comment]
downgrading my Comfy UI and Animate Diff has fixed the issue. Not sure why
the upgrades aren't working properly but I can use the downgraded versions
for now. Thanks

**Comment by jav12z** [comment]
I have the same issue, I tried with the Commits on Oct 26, 2023 version 2b04d95, and it works as it should without downgrading comfyUI

**Comment by Boldor83** [comment]
might be new issue, but after the latest update it no longer ignores the next prompt but the scheduling doesn't work right either. now everything in the box gets merged together. For example

"0": "a young woman in spring",
"20": "a young woman in autumn",
"40": "a young woman in winter"

has a mix of the 3 seasons right from the beginning, same with red cat and blue dog creates a mix of both.
![AnimateDiff_00202_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/120499637/e8724a8b-c288-437d-ae2c-ef6305b585ac)
![AnimateDiff_00201_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/120499637/2899433d-0306-4c6f-8981-37168e5a1525)

i attached two pngs with workflow. it worked with this kind of workflow before.

**Comment by Boldor83** [comment]
replacing BatchPromptSchedule with BatchPromptSchedule(LatentInput) the transition works, but the behavior seems a little different. when starting at 20 with 40 latent input the transition starts very fast, putting start of the prompt at 40 its more even.

**Comment by Boldor83** [comment]
Alright the culprit was max frames not being same as latent batch. this wasn't breaking the workflow to behave wrong before, if its same it works again.
