### ISSUE TITLE
一个不生效的问题

### ISSUE THREAD

**Issue by i30226** [FizzleDorf/ComfyUI_FizzNodes#27]
我将它下载到我的custom_nodes文件夹里，他不启用，进入comfyUI里也没有相关节点

**Comment by 779575267** [comment]
同意

**Comment by min-star** [comment]
the same peoblem

**Comment by min-star** [comment]
the same problem

**Comment by LeoMusk** [comment]
有解决吗？老铁，我也是这个问题。控制台报错：
ImportError: DLL load failed while importing strptime: 拒绝访问。

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: DLL load failed while importing strptime: 拒绝访问。
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data

**Comment by FizzleDorf** [comment]
ルート・フォルダーで次のコマンドを使う。
`.\python_embed\python.exe -s -m pip install -r requirements.txt` 

を使うこともできる：
https://github.com/ltdrdata/ComfyUI-Manager

*日本語が下手でごめんなさい。まだ勉強中です。*

**Comment by LeoMusk** [comment]
> 有解决吗？老铁，我也是这个问题。控制台报错： ImportError: DLL load failed while importing strptime: 拒绝访问。
> 
> Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: DLL load failed while importing strptime: 拒绝访问。 Traceback (most recent call last): File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 879, in exec_module File "", line 1016, in get_code File "", line 1073, in get_data

知道原因了：有个embeded里面的文件被杀毒软件给当成病毒清了，恢复后就能用了
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/112799185/21e5d62f-8fcc-45f9-892a-670c76721bcf)
