### ISSUE TITLE
Small prompt window

### ISSUE THREAD

**Issue by jlitz** [FizzleDorf/ComfyUI_FizzNodes#36]
my prompt window is narrow for some reason.  Is there a way of expanding  it?   https://i.imgur.com/15A6vVD.png    tia

**Comment by FizzleDorf** [comment]
if you hover the cursor over the bottom-right corner of the node, you can resize it so the inputs have more room. An alternative is right click the node, change all the text widgets into inputs, then double-click the input for primitives you can resize as well.

**Comment by jlitz** [comment]
tnx,   the resize with the right corner and change text widgets to inputs helps,   I do not understand double clicking primitives.  What are the primitives?    I  was thinking the ability to resize each section would be nice.     Just getting started in comfy so forgive my ignorance.

**Comment by FizzleDorf** [comment]
when you right click the node you will seer options like this:
![1](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/50044ab0-e015-493c-9018-55ac0c4fe520)
you should see inputs like this now. Double click on the ones circled:
![2](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/4970b57f-8c3d-40ca-9126-6c5ae2ac81a1)
you should have multiline primitive nodes to place wherever you find convenient:
![3](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/290ba781-b41d-42bb-a97d-3e91003a3293)

**Comment by jlitz** [comment]
ah ok  that works tnx much for your work
