### ISSUE TITLE
Prompt travel not working, error points to incompatible dtype.

### ISSUE THREAD

**Issue by grimsanta85** [FizzleDorf/ComfyUI_FizzNodes#38]
I am receiving this error: 

> ComfyUI_FizzNodes\BatchFuncs.py:128: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
> cur_prompt_series[f] = ''

I receive this on line 129 as well. If I set those variables to None, it resolves the error but then the same error occurs on lines 131 and 132. 

I have updated and regressed my pandas version as well to no avail. 

Thank you for all you do.

**Comment by FizzleDorf** [comment]
Sorry I didn't get to an answer sooner, this was actioned in a commit a long while ago. If you still have the issue, leave a comment here and I'll reopen the issue.

**Comment by gateway** [comment]
so I just noticed this as well, I'm not sure if i did something wrong.. this is for sd1.5

![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/519563/d1650dd0-90bb-45f2-b686-cd3cfc9d1266)
