### ISSUE TITLE
OMG I have discovered the Holy Grail!!!!!

### ISSUE THREAD

**Issue by AIMusicExperiment** [FizzleDorf/ComfyUI_FizzNodes#4]
Not an issue, but I just wanted to thank you for your nodes, particularly the prompt scheduler.  I am currently developing a custom workflow along with "ComfyRoll." It is a variation on the Deforum Hybrid Video function. We were stymied as to how to do the prompt scheduling that we needed, until Suzie stumbled across your nodes! This is exactly what we needed and more! May much good fortune reign down upon you! Thanks for being awesome!

**Comment by mattymatty** [comment]
can you share the comfy workflow?
