### ISSUE TITLE
I tried so many times, I don't know what went wrong，  IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by xunte** [FizzleDorf/ComfyUI_FizzNodes#40]
D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py:129: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  nxt_prompt_series[f] = ''
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 124, in animate
    pos_cur_prompt, pos_nxt_prompt, weight = interpolate_prompt_series(pos, max_frames, start_frame, pre_text, app_text, pw_a, pw_b, pw_c, pw_d, print_output)
  File "D:\SD\Comfyui\ComfyUI_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py", line 167, in interpolate_prompt_series
    cur_prompt_series[index_offset] = prepare_batch_prompt(cur_prompt_series[i], max_frames, i, prompt_weight_1[i],
IndexError: invalid index to scalar variable.

 ComfyUI Revision: 1699 [0cf4e869] | Released on '2023-11-17'

![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/58557441/c2ad7929-ccb3-4018-9914-7585b7ad2e01)

**Comment by FizzleDorf** [comment]
you need the batch value schedule, not the regular one
![Capture](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/6254fc08-5929-4f20-99af-a6335389eea0)

**Comment by xunte** [comment]
Thank you very much, very much
Excuse me, but can I ask you another question: Using animatediff text to generate video, how can I load non-weighted lora with different frames



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 24, 2023 15:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FizzleDorf/ComfyUI_FizzNodes] I tried so many times, I don't know what went wrong，  IndexError: invalid index to scalar variable. (Issue #40)




 
you need the batch value schedule, not the regular one
