### ISSUE TITLE
Error occurred when executing BatchPromptSchedule: Sizes of tensors must match except in dimension 0.

### ISSUE THREAD

**Issue by lp880** [FizzleDorf/ComfyUI_FizzNodes#62]
Error occurred when executing BatchPromptSchedule:
Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 12 in the list.

Hello, I give this error when I use this prompt, I try to reduce or increase the number of characters in 12 keyframe and it give same error but with tensor number 48. 

After Adjust entire prompt it will work but I don't know what cause error.
Length inconsistency, the fact that a certain number of characters are exceeded compared to the first prompt, or a minimum number of characters compared to the previous prompt

This is the prompt

"1": "with a sleek, short bob haircut, characteristic of the early 1990s. She's wearing a bright neon windbreaker, large hoop earrings, and bold, geometric-patterned leggings. The background is an urban setting with graffiti art, reflecting the vibrant street culture of the era.",

"12": "embodying the grunge fashion of the mid-1990s. She has long, unkempt hair, dark eyeliner, and a flannel shirt tied around her waist. Her outfit includes a band T-shirt and ripped jeans, complemented by a pair of well-worn combat boots. The setting is a dimly lit, retro coffee shop.",

"24": "showcasing the minimalist fashion trend. She has a sleek, straight hairstyle, middle-parted. She's dressed in a simple, elegant slip dress in a pastel color, paired with a delicate choker necklace and strappy sandals. The background is a minimalist, chic urban apartment",

"48": "Early 2000s style, featuring a woman with chunky highlights in her hair and a glossy lip. She's wearing a bright, Juicy Couture tracksuit, paired with a tank top with a glittery graphic. Accessories include a large, metallic handbag and platform sneakers. The setting is a bustling shopping mall.",

"60": "Mid-2000s fashion, with a woman sporting a side-swept bangs hairstyle and smoky eye makeup. Her outfit consists of a layered tank top over a lace-trimmed camisole, low-rise bootcut jeans, and a wide studded belt. She's wearing pointy-toe stiletto heels. The background is a trendy nightclub scene",

"72": "Late 2000s elegance, featuring a woman with a soft, wavy hairstyle and natural makeup. She's dressed in a sophisticated empire waist dress with floral prints, paired with a cropped cardigan and ballet flats. The setting is a serene, sunlit garden with blooming flowers",

"84": "Early 2010s hipster fashion, with a woman sporting ombre hair and thick-rimmed glasses. She's wearing a vintage graphic tee, high-waisted shorts, and a plaid shirt tied around her waist. Her look is completed with a pair of classic Converse sneakers. The background is an artsy, urban café.",

"96": "Mid-2010s style, featuring a woman with a lob (long bob) haircut and bold, contoured makeup. She's dressed in a chic, off-shoulder top, ripped skinny jeans, and ankle boots. Accessories include a statement necklace and a clutch. The setting is a modern, upscale bar.",

"108": "Late 2010s trend, with a woman flaunting a beachy waves hairstyle and glowing, dewy makeup. Her outfit is a boho-chic maxi dress, layered with a denim jacket, and accessorized with a wide-brimmed hat and ankle-strap sandals. The background is a picturesque beach at sunset.",

"120": "Contemporary 2020s fashion, showcasing a woman with a sleek, high ponytail and minimalist makeup. She's wearing a monochrome, tailored pantsuit with a turtleneck sweater, complemented by minimalist jewelry and sleek, pointed-toe heels. The setting is a modern, architecturally striking office space."
can you resolve Prompt Lengths

**Comment by FizzleDorf** [comment]
there are multiple fixes for this. one is using this PR #61. another is to pad the tokens using commas `,` in the shorter prompt to match the token chunk size. Lastly, I have a branch open for the [actual fix](https://github.com/FizzleDorf/ComfyUI_FizzNodes/tree/cond_size_fix) although the quality isn't very good at the moment.

**Comment by lp880** [comment]
Thanks for the quick and prompt reply, it seems to work with the addition of the code provided by @aiXanderaiXander, I thought it was something related to tokenization but I didn't know where exactly. Thank you.

**Comment by FizzleDorf** [comment]
#64 fixed this issue

**Comment by chieeo** [comment]
Error occurred when executing BatchPromptSchedule:
Expecting ':' delimiter: line 1 column 11 (char 10)
i have no idea about this,help me
