### ISSUE TITLE
IndexError: invalid index to scalar variable when run Simple Animation Workflow example

### ISSUE THREAD

**Issue by emourdavid** [FizzleDorf/ComfyUI_FizzNodes#63]
When I run workflow of Simple Animation Workflow example. I got this issue. How can I solve this and prevent this problem for later
https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/8899f25e-fbc8-423c-bef2-e7c5a91fb7f4 

![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/139842563/5512342c-3324-41da-a3f7-18000e37fcb1)

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\1.ext_tools\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\1.ext_tools\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\1.ext_tools\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\1.ext_tools\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 81, in animate
    pos_cur_prompt, pos_nxt_prompt, weight = interpolate_prompt_series(pos, max_frames, start_frame, pre_text, app_text, pw_a,
  File "E:\1.ext_tools\ComfyUI\custom_nodes\ComfyUI_FizzNodes\BatchFuncs.py", line 153, in interpolate_prompt_series
    cur_prompt_series[i] = prepare_batch_prompt(cur_prompt_series[i], max_frames, i, float(prompt_weight_1[0]),
IndexError: invalid index to scalar variable.

Thank you.

**Comment by FizzleDorf** [comment]
fixed in [90d69fa](https://github.com/FizzleDorf/ComfyUI_FizzNodes/commit/90d69fab6d6903aeec9f7eb75946cb7ce33fa84a). apologies I didn't catch this sooner
