### ISSUE TITLE
The strength don't change when using SXDL batch prompt schedule

### ISSUE THREAD

**Issue by xianienie** [FizzleDorf/ComfyUI_FizzNodes#68]
![{D4778267-5C78-49f5-8F76-157194E632AF}](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113016462/707fa08a-d98f-493e-beba-bc3d56f8b8d8)
print output:Max Frames:  36 
 Current Prompt G:  (masterpiece,best quality:1.2),(energy flow,magic:1.3),mysterious,bird,shot of peahen, super-detailed intricate, taken by David LaChapelle, ligtning, bioluminescent, reflecting,smoke, particles,from side，a peacock spreads its tail feathers (ice:1.7) 
 Current Prompt L:  (masterpiece,best quality:1.2),(energy flow,magic:1.3),mysterious,bird,shot of peahen, super-detailed intricate, taken by David LaChapelle, ligtning, bioluminescent, reflecting,smoke, particles,from side，a peacock spreads its tail feathers (ice:1.7) 
 Next Prompt G:  (masterpiece,best quality:1.2),(energy flow,magic:1.3),mysterious,bird,shot of peahen, super-detailed intricate, taken by David LaChapelle, ligtning, bioluminescent, reflecting,smoke, particles,from side，a peacock spreads its tail feathers (lightning:1.7) 
 Next Prompt L :  (masterpiece,best quality:1.2),(energy flow,magic:1.3),mysterious,bird,shot of peahen, super-detailed intricate, taken by David LaChapelle, ligtning, bioluminescent, reflecting,smoke, particles,from side，a peacock spreads its tail feathers (lightning:1.7) 

Repeat 36 times. And I couldn't find any difference in it.

**Comment by xianienie** [comment]
And the example workflow don't work
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/113016462/38adf954-2f5d-40d8-8cb3-b45dbda9ac0f)

**Comment by FizzleDorf** [comment]
a696099 fixes this issue. thanks for your patience.
