### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by Jimmylong473** [FizzleDorf/ComfyUI_FizzNodes#70]
try to install in the comfyui manager or manually lots of time, all import failed and can't find fizz in the working zone.
![屏幕截图 2024-02-28 133651](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/161558166/7357d70b-205d-4731-8273-0f977012a756)
can anyone help me ? thanks

**Comment by jaka-k** [comment]
Updated Comfy UI

**Comment by FizzleDorf** [comment]
@Jimmylong473 are you still experiencing the issue after updating comfyui?

**Comment by haohaocreates** [comment]
@Jimmylong473 I had the same error for FizzleDorf but after updating comfyui from the manager and then restarting my session, the error went away!
