### ISSUE TITLE
`pre_text` and `app_text` ignored entirely in `BatchStringSchedule`

### ISSUE THREAD

**Issue by atmaranto** [FizzleDorf/ComfyUI_FizzNodes#71]
Because the `interpolate_prompt_series` function in `BatchFuncs.py` ignores the `pre_text` and `app_text` arguments, they are never used for the `BatchStringSchedule` node. As a result, the node will ignore these values when specified in the UI.

![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/35581227/3a13ddde-366f-41f9-a266-a5857d934528)

**Comment by FizzleDorf** [comment]
I fixed the issue in f36cfef
