### ISSUE TITLE
Prompt Schedule SDXL seems to ignore "current_frame "

### ISSUE THREAD

**Issue by total1ty** [FizzleDorf/ComfyUI_FizzNodes#75]
Title says it all, the node always acts like current_frame is 0.

I've investigated this using a setup where I can A/B test the regular Prompt Schedule node vs. the SDXL, and the regular one works just fine using exactly the same inputs and prompts. So formatting errors in the scheduling are out of the question.

Frankly, I'm not exactly sure if I'm using the SDXL node correctly. But since changing the prompt at 0 works fine I suspect the node doing (un)fancy things.

Here is my testing setup, just reconnect the Reroutes before the sampler and edit the cyan frame# node between 0/100:

![ComfyUI_temp_lrcto_00199_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/803350/be3137f4-7a66-44fd-8241-4987a0b14abf)

**Comment by total1ty** [comment]
I just added a third keyframe to the list and now it works, but ignores the last keyframe. So I added another "dummy" keyframe at the end, and now it basically works.. I dont know, maybe this could be the same reason for https://github.com/FizzleDorf/ComfyUI_FizzNodes/issues/73

Here is the updated test setup:
![ComfyUI_temp_lrcto_00229_](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/803350/7694af46-433d-4741-a982-075ac752b255)

The console log shows the correct strengths and prompts:

`100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.44it/s]
Prompt executed in 4.02 seconds
got prompt

 G_Clip:
 Max Frames:  9999
 Current Prompt:  beautiful scenery nature glass bottle landscape, , purple galaxy bottle,
 Next Prompt:  apocalyptic scenery industrial bottle landscape, , green galaxy bottle,
 Strength :  0.5800000000000001


 L_Clip:
 Max Frames:  9999
 Current Prompt:  beautiful scenery nature glass bottle landscape, , purple galaxy bottle,
 Next Prompt:  apocalyptic scenery industrial bottle landscape, , green galaxy bottle,
 Strength :  0.5800000000000001

100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.25it/s]
Prompt executed in 4.15 seconds
got prompt

 G_Clip:
 Max Frames:  9999
 Current Prompt:  apocalyptic scenery industrial bottle landscape, , green galaxy bottle,
 Next Prompt:  arctic scenery bottle landscape, , white galaxy bottle,
 Strength :  0.63


 L_Clip:
 Max Frames:  9999
 Current Prompt:  apocalyptic scenery industrial bottle landscape, , green galaxy bottle,
 Next Prompt:  arctic scenery bottle landscape, , white galaxy bottle,
 Strength :  0.63`

**Comment by FizzleDorf** [comment]
a696099 fixes this issue. you should be able to get a proper result in your examples. thank you for providing them!
