### ISSUE TITLE
if max_size is 0 in some files, thows a warning.

### ISSUE THREAD

**Issue by dlandry** [FizzleDorf/ComfyUI_FizzNodes#81]
When I install the node it shows the following WARNINGS during startup.

/var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI_FizzNodes/ScheduleFuncs.py:26: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if max_size is 0:
/var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py:178: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if max_size is 0:

Since it's just a syntax "warning" I assume it's not making a big difference, but I changed the code in those two files to "if max_size ==0" anyway  just to make the startup cleaner.

Not sure if it's me using an outdated version of Python, or if you did the "is" for a reason. Anyway no biggie. Just thought I'd mention it in case this was something you wanted to fix, or set me straight on its use. ;-)

**Comment by FizzleDorf** [comment]
no worries. I made the change in fd21651
