### ISSUE TITLE
works beautifully - noticed one bug/behavior

### ISSUE THREAD

**Issue by ryanontheinside** [FizzleDorf/ComfyUI_FizzNodes#82]
Thank you for this amazing node. I do occasionally get the following error. It seems to happen when one of the prompts is too long. It does not appear to be caused by the number of prompts, just when one of them exceeds some length.

"Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 224 in the list."

**Comment by FizzleDorf** [comment]
hey @ryanontheinside, I've seen another issue opened on the same bug but I'm having trouble reproducing it. could you provide more info about what prompt you are using and if you are updated to the latest version of the node?

**Comment by FizzleDorf** [comment]
the most recent push should solve the issue
