### ISSUE TITLE
dtype float64

### ISSUE THREAD

**Issue by hahy36** [FizzleDorf/ComfyUI_FizzNodes#84]
![Uploading 2024-04-13_11.28.06.jpg…]()

**Comment by hahy36** [comment]
Loading 1 new model
/kaggle/working/ComfyUI/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py:143: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A beautiful Japanese girl dancing, kimono-clad, cherry blossoms swirling around her, graceful movements, soft light filtering through branches, traditional accessories, intricate obi sash, flowing hair, serene expression, long eyelashes, delicate nose, full lips, (best quality, 4k, 8k, highres, masterpiece: 1.2), ultra-detailed, (realistic, photorealistic, photo-realistic: 1.37), fine art, oil painting, vibrant pinks, warm yellows,  A beautiful Japanese girl dancing, kimono-clad, cherry blossoms swirling around her, graceful movements atmospheric glow, natural shadows, bokeh background.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  cur_prompt_series[f] = str(current_prompt)
/kaggle/working/ComfyUI/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py:144: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A beautiful Japanese girl dancing, kimono-clad, cherry blossoms swirling around her, graceful movements, soft light filtering through branches, traditional accessories, intricate obi sash, flowing hair, serene expression, long eyelashes, delicate nose, full lips, (best quality, 4k, 8k, highres, masterpiece: 1.2), ultra-detailed, (realistic, photorealistic, photo-realistic: 1.37), fine art, oil painting, vibrant pinks, warm yellows,  A beautiful Japanese girl dancing, kimono-clad, cherry blossoms swirling around her, graceful movements atmospheric glow, natural shadows, bokeh background.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  nxt_prompt_series[f] = str(next_prompt)
Requested to load SD1ClipModel
Loading 1 new model
/kaggle/working/ComfyUI/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py:143: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '  ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  cur_prompt_series[f] = str(current_prompt)
/kaggle/working/ComfyUI/custom_nodes/ComfyUI_FizzNodes/BatchFuncs.py:144: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '  ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  nxt_prompt_series[f] = str(next_prompt)

**Comment by FizzleDorf** [comment]
this seems to be an older version. the line isn't matching with what I have in the latest code. have you updated?

**Comment by hahy36** [comment]
I am using the latest version of fizznodes.

**Comment by FizzleDorf** [comment]
this PR fixes this error #98
