### ISSUE TITLE
Its back?

### ISSUE THREAD

**Issue by NullEqualsZero** [FizzleDorf/ComfyUI_FizzNodes#87]
Due to GPU limitations, I haven't used the node for a few months. Finally, I managed to upgrade my GPU. It usually works fine but sometimes when you change something in the prompt I get this error which doesn't want to stop.

`The size of tensor a (77) must match the size of tensor b (154) at non-singleton dimension 1`

**Comment by FizzleDorf** [comment]
yeah, I'm in the middle of refactoring and making sure the padding is going to apply correctly. I'm hoping things are back to normal today to begin adding additional functionality and some more examples

**Comment by NullEqualsZero** [comment]
oh perfect thank you. It is weird, it is better than before. If I remove a few prompts it works fine. It is like there is a limit on the token size allowed (or whatever the correct name is)
