### ISSUE TITLE
Error occurred when executing BatchPromptSchedule:  Expecting value: line 1 column 7 (char 6)

### ISSUE THREAD

**Issue by chieeo** [FizzleDorf/ComfyUI_FizzNodes#89]
what happened

**Comment by FizzleDorf** [comment]
can you provide the prompt and the full traceback? I can't tell if this is
a syntax error or something in code

**Comment by linnkoln** [comment]
![image](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/60001135/6a2ac8cb-a84e-4806-ae7b-2d897bf150f8)

**Comment by Aztec4269** [comment]
I'm having the same exact issue

**Comment by FizzleDorf** [comment]
I haven't been able to recreate this issue. try pulling to the latest version. I'll close this issue for now but will reopen it if you are still having trouble. 
 
![Capture](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/46942135/57d45dee-cf6b-4791-b566-eec781a16aa9)
