### ISSUE TITLE
String Concatenate node returns trailing comma

### ISSUE THREAD

**Issue by Pos13** [FizzleDorf/ComfyUI_FizzNodes#94]
String Concatenate node returns trailing comma.
`"0": "text_a","12": "text_b","72": "text_g",`

**Comment by FizzleDorf** [comment]
Hey @Pos13, the schedule nodes automatically remove trailing commas for quick copy pasting in the schedule text. I hope this helps

**Comment by Pos13** [comment]
@FizzleDorf, sorry, I was confused by the entry in [Fizznodes Wiki](https://github.com/FizzleDorf/ComfyUI_FizzNodes/wiki/Prompt-Schedules#prompt-syntax):

_"If you plan on having another keyframed prompt after this one, you need to place a comma (`,`) after the closing quote of your last prompt. If you don't do this you will get an error. **If it is your last prompt do not place a comma as this will result in an error as well.**"_
