### ISSUE TITLE
When I input 50 for "start_frame", it does not start from the prompt of frame 50, but instead starts from the prompt of frame 0.

### ISSUE THREAD

**Issue by 957057** [FizzleDorf/ComfyUI_FizzNodes#95]
![QQ截图20240521095556](https://github.com/FizzleDorf/ComfyUI_FizzNodes/assets/74393034/c5bafcda-c25a-413b-9354-cd89c9fff16b)
When I input 50 for "start_frame", it does not start from the prompt of frame 50, but instead starts from the prompt of frame 0.

**Comment by chris-arsenault** [comment]
start and end only seem to control the prompt regexing (possible bug?). I found adding a settings param here:
https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/main/BatchFuncs.py#L316
and then changing the loops on lns: 321 and 325 to look at start/end to work for me

**Comment by FizzleDorf** [comment]
I added this to the latest commit da49dd3
