### ISSUE TITLE
Import Failed every time, need to "Try Fix" to run it

### ISSUE THREAD

**Issue by dreamlogic-X** [FizzleDorf/ComfyUI_FizzNodes#99]
Hi, I'm having an issue that every time I start up ComfyUI, ComfyUI_FizzNodes fails to import. 

I run "Try Fix" in the manager and then after restarting it works. 

Would be great to have this looked at. Thanks a lot.

**Comment by FizzleDorf** [comment]
This is more an issue with the comfyui manager than this repo. Seems to happen on a couple of extensions

**Comment by dreamlogic-X** [comment]
Oh okay, thanks for letting me know. I'll flag it in that repo.
